server:
  address: "localhost"
  port: 8080

database:
  user: "postgres"
  dbname: "cyber_garden"
  host: "localhost"
  port: 5432
  sslmode: "disable"

logger_level: "debug"

recognize_api:
  max_images: 5
  base_url: "https://my-api.plantnet.org/v2/identify/"
  count_results: 5
  image_field: "images"
  token: "2b109QtPNL155fUgf3usDHvsk"

trefle_api:
  base_url: "https://trefle.io/api/v1/plants/"
  count_plants: 20
  token: "lFS3BajmCiFb4Qn20NFwLlCg8VGQh8BFboWuratD5qw"

perenaul_api:
  base_url: "https://www.perenual.com/api"
  token: "sk-2Szd653289133ea802582"

cookie_settings:
  secure: "true"
  http_only: "true"
  expire_date:
    years: 0
    months: 0
    days: 7
