server:
  address: "localhost"
  port: 8080

database:
  user: "postgres"
  dbname: "cyber_garden"
  host: "localhost"
  port: 5432
  sslmode: "disable"

logger_level: "debug"

cookie_settings:
  secure: "true"
  http_only: "true"
  expire_date:
    years: 0
    months: 0
    days: 7
